version: '3.1'

services:
  my-nuxt-app:
    build: ./nuxt/
    container_name: my-nuxt-app
    restart: unless-stopped
    ports:
      - 3000:3000
  my-db-pg:
    image: postgres:16.1-alpine3.17
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=bitok
      - POSTGRES_USER=bitok
      - POSTGRES_DB=bitok